version: '3'

tasks:
  build:
    desc: Build the application
    cmds:
      - mkdir -p .build
      - go build -o .build/dependabot-pr-checker

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...
      
  coverage:
    desc: Measure test coverage
    cmds:
      - mkdir -p .build
      - go test -coverprofile=.build/coverage.out ./...
      - go tool cover -func=.build/coverage.out

  coverage-report:
    desc: Generate HTML test coverage report
    deps: [coverage]
    cmds:
      - go tool cover -html=.build/coverage.out -o .build/coverage.html
      - echo "Coverage report generated at .build/coverage.html"